### ISSUE TITLE
Steuerung via Alexa funktioniert noch nicht

### ISSUE THREAD

**Issue by TTRCmedia** [Monarch73/RFBridge2#1]
Echo 1st. Gen, Dot2 und Show vorhanden. Gespeicherte Lampen wurden durch die Suche via Alexa-App gefunden. Die Steuerung via Webinterface funktioniert, es wird der hinterlegte Code gesendet.

![img_1294](https://user-images.githubusercontent.com/35400401/34909741-45487eba-f8a7-11e7-876f-871e5aaae65f.JPG)

Die Steuerung über die Alexa-App oder Sprachkommandos funktioniert leider noch nicht, es wird kein Code gesendet. D4 bleibt bei 0V-Pegel.

![img_1295](https://user-images.githubusercontent.com/35400401/34909742-4c771c1e-f8a7-11e7-9277-f4021e7eec94.JPG)

**Comment by Monarch73** [comment]
Ich bräuchte noch ein paar Infos:

- Was antwortet Alexa auf "schalte xyz ein"?
- Funktioniert die Steuerung per Alexa-App im "Smárt Home" bereich?
- Log-Auszug vom seriellen Monitor ab dem Zeitpunkt, wo die Bridge eigentlich schalten sollte

Danke im vorraus.

**Comment by TTRCmedia** [comment]
- Alexas Antwort ist "OK"
- Steuerung via Alexa-App im Bereich "Smart Home" funktioniert nicht (meinte ich oben mit "über die Alexa-App")
- Log

Beim Schalten über das WebInterface:
> turning light on
> turning light off

Beim Schalten via Alexa-App -> Smart Home oder Sprachkommando:
> Reply by Light
> Reply by Lightscontrol
> 0
> Reply by Light
> Reply by Light

**Comment by Monarch73** [comment]
Danke für die Rückmeldung. Leider fehlen mir wichtige Debug-Informationen. Ich habe den Log-Level in diesen Binaries erhöht:
[RFBridge2.zip](https://github.com/Monarch73/RFBridge2/files/1628862/RFBridge2.zip)

**Comment by e485s** [comment]
Hier meine erfolgreichen Tests mit der Version ohne Debug-Informationen,
ich verwende ein NodeMcu V3 LoLin:





Start: 74880 Baud


 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v00000000

Start: 115200 Baud


Filesize failed
Initializing file contents
No ssid defined
AP IP address: 192.168.4.1

Mit AP Verbinden:

add 1
     aid 1
          station: 90:8d:6c:45:62:24 join, AID = 1


Webseite 192.168.4.1 aufrufen:

                                                  New client
method: GET url: / search:
headerName: Host
headerValue: 192.168.4.1
headerName: Upgrade-Insecure-Requests
headerValue: 1
headerName: Accept
headerValue: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
headerName: User-Agent
headerValue: Mozilla/5.0 (iPad; CPU OS 11_0_2 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) CriOS/63.0.3239.73 Mobile/15A421 Safari/604.1
headerName: Accept-Language
headerValue: de-de
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Connection
headerValue: keep-alive
args:
Request: /
 Arguments:
New client
method: GET url: / search:
headerName: Host
headerValue: 192.168.4.1
headerName: Upgrade-Insecure-Requests
headerValue: 1
headerName: Accept
headerValue: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
headerName: User-Agent
headerValue: Mozilla/5.0 (iPad; CPU OS 11_0_2 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) CriOS/63.0.3239.73 Mobile/15A421 Safari/604.1
headerName: Accept-Language
headerValue: de-de
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Connection
headerValue: keep-alive
args:
Request: /
 Arguments:

Zugangsdaten eingeben incl initialize Storage "Haken"

New client
method: POST url: /setup search:
headerName: Host
headerValue: 192.168.4.1
headerName: Content-Type
headerValue: application/x-www-form-urlencoded
headerName: Origin
headerValue: http://192.168.4.1
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Connection
headerValue: keep-alive
headerName: Upgrade-Insecure-Requests
headerValue: 1
headerName: Accept
headerValue: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
headerName: User-Agent
headerValue: Mozilla/5.0 (iPad; CPU OS 11_0_2 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) CriOS/63.0.3239.73 Mobile/15A421 Safari/604.1
headerName: Referer
headerValue: http://192.168.4.1/
headerName: Content-Length
headerValue: 66
headerName: Accept-Language
headerValue: de-de
args: ssid=SmartHome&password=XXXXXXXXXXXXXXXXXX&format=format&send=save
args count: 4
pos 0=@ 4 &@ 14
arg 0 key: ssid value: SmartHome
pos 15=@ 23 &@ 42
arg 1 key: password value: XXXXXXXXXXXXXXXXXX
pos 43=@ 49 &@ 56
arg 2 key: format value: format
pos 57=@ 61 &@ -1
arg 3 key: send value: save
args count: 4
Plain: ssid=SmartHome&password=XXXXXXXXXXXXXXXXXX&format=format&send=save
Request: /setup
 Arguments: ssid=SmartHome&password=XXXXXXXXXXXXXXXXXX&format=format&send=save
Filesize failed
Initializing file contents

Reboot über RST Taste

Exception (0):
epc1=0xe14c2fd5 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont
          sp: 3fff18a0 end: 3fff1cd0 offset: 01a0

>>>stack>>>
           3fff1a40:  0000002e 3fff221c 3fff2c54 401046f1
3fff1a50:  3fff2804 3fff30a0 00000001 3fff30b0
3fff1a60:  00000dd8 3fff2c7c 00000000 3fff2251
3fff1a70:  3fff221c 3fff221c 3fff2804 4010485d
3fff1a80:  4021cb17 3fff2804 3fff284a 4021cb20
3fff1a90:  00000008 3fff1ac0 3ffef698 4022cf0c
3fff1aa0:  3ffef04c 4022c88a 3ffeef8c 3fff2858
3fff1ab0:  3fff2804 3fff2d08 3fff221c 40222bb5
3fff1ac0:  005e0001 3ffefb00 00000012 4022cf0c
3fff1ad0:  00000018 3fff2d08 3fff2804 4022363c
3fff1ae0:  00000080 4022a936 3fff0c98 00000000
3fff1af0:  3fff2220 00000001 00000000 00000002
3fff1b00:  3fff2174 00000004 3fff2d04 40223cb4
3fff1b10:  4023ec13 3fff0438 3fff0488 3fff2d04
3fff1b20:  00000000 3fff2804 3fff2870 4022367c
3fff1b30:  3fff221c 3fff1b60 00000004 3fff2d04
3fff1b40:  00000016 3fff221c 3fff2d04 40222e0d
3fff1b50:  3fff221c 3fff1b60 00000004 4021cb7c
3fff1b60:  00000494 00000000 3fff23ac 4021cbb8
3fff1b70:  3fff2d08 3fff221c 3fff0c98 40222ede
3fff1b80:  3fff2c7c 3fff0864 0000001c 00000020
3fff1b90:  3fff1bfc 3fff221c 3fff2d04 402230b7
3fff1ba0:  3fff1bfc 3ffea8a0 3fff221c 40223143
3fff1bb0:  3fff2c00 00000001 3fff1c30 00000001
3fff1bc0:  3fff0930 3fff0860 3fff0930 40210f56
3fff1bd0:  00000000 3fff0860 3fff2b44 401009a4
3fff1be0:  3fff0c98 00000187 3fff1c20 40212744
3fff1bf0:  00000000 3fff0860 3fff095c fb0000e0
3fff1c00:  00000000 3fff0860 3fff0930 3fff041c
3fff1c10:  00000000 3fff0860 3fff0930 402123ee
3fff1c20:  3fff2b4c 4020bea4 40210de8 40211078
3fff1c30:  00000000 00000000 3fff0860 4020c089
3fff1c40:  3fff0488 3fff0860 3fff1d18 40207729
3fff1c50:  00000000 00000000 00000000 feefeffe
3fff1c60:  00000000 00000000 00000000 00000000
3fff1c70:  00000000 00000000 3fff3504 0000001f
3fff1c80:  00000010 feefeffe feefeffe feefeffe
3fff1c90:  00000001 feefeffe feefeffe feefeffe
3fff1ca0:  feefeffe feefeffe feefeffe 3fff0ca4
3fff1cb0:  3fffdad0 00000000 3fff0c9c 4021293f
3fff1cc0:  feefeffe feefeffe 3fff0cb0 40100a28
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v00000000
~ld
   1
Hue Emulation startet: 192.168.179.31
Starting SSDP...
SSDP Started
pm open,type:2 0


Mit "Webseite" verbinden
                New client
method: GET url: /jsonList search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Connection
headerValue: keep-alive
headerName: Accept
headerValue: application/json, text/plain, */*
headerName: User-Agent
headerValue: Mozilla/5.0 (iPad; CPU OS 11_0_2 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A421 Safari/604.1
headerName: Accept-Language
headerValue: de-de
headerName: Referer
headerValue: http://192.168.179.31/
headerName: DNT
headerValue: 1
args:
Request: /jsonList
 Arguments:

Gerät eintragen und abspeichern

New client
method: POST url: /estore search:
headerName: Host
headerValue: 192.168.179.31
headerName: Content-Type
headerValue: application/x-www-form-urlencoded;charset=UTF-8
headerName: Origin
headerValue: http://192.168.179.31
headerName: Accept-Language
headerValue: de-de
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Connection
headerValue: keep-alive
headerName: Accept
headerValue: application/json, text/plain, */*
headerName: User-Agent
headerValue: Mozilla/5.0 (iPad; CPU OS 11_0_2 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A421 Safari/604.1
headerName: Referer
headerValue: http://192.168.179.31/
headerName: DNT
headerValue: 1
headerName: Content-Length
headerValue: 82
args: name=SteckdoseA&house=11111&code=100000&tri1=&tri2=&url1=&url2=&irhz=&iroff=&iron=
args count: 10
pos 0=@ 4 &@ 15
arg 0 key: name value: SteckdoseA
pos 16=@ 21 &@ 27
arg 1 key: house value: 11111
pos 28=@ 32 &@ 39
arg 2 key: code value: 100000
pos 40=@ 44 &@ 45
arg 3 key: tri1 value:
pos 46=@ 50 &@ 51
arg 4 key: tri2 value:
pos 52=@ 56 &@ 57
arg 5 key: url1 value:
pos 58=@ 62 &@ 63
arg 6 key: url2 value:
pos 64=@ 68 &@ 69
arg 7 key: irhz value:
pos 70=@ 75 &@ 76
arg 8 key: iroff value:
pos 77=@ 81 &@ -1
arg 9 key: iron value:
args count: 10
Plain: name=SteckdoseA&house=11111&code=100000&tri1=&tri2=&url1=&url2=&irhz=&iroff=&iron=
Request: /estore
 Arguments: name=SteckdoseA&house=11111&code=100000&tri1=&tri2=&url1=&url2=&irhz=&iroff=&iron=
storing
SteckdoseA
11111
100000




New client
method: GET url: /jsonList search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Connection
headerValue: keep-alive
headerName: Accept
headerValue: application/json, text/plain, */*
headerName: User-Agent
headerValue: Mozilla/5.0 (iPad; CPU OS 11_0_2 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A421 Safari/604.1
headerName: Accept-Language
headerValue: de-de
headerName: Referer
headerValue: http://192.168.179.31/
headerName: DNT
headerValue: 1
args:
Request: /jsonList
 Arguments:

Steckdose einschalten über Webinterface

New client
method: GET url: /esocket search: no=0&sw=1
headerName: Host
headerValue: 192.168.179.31
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Connection
headerValue: keep-alive
headerName: Accept
headerValue: application/json, text/plain, */*
headerName: User-Agent
headerValue: Mozilla/5.0 (iPad; CPU OS 11_0_2 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A421 Safari/604.1
headerName: Accept-Language
headerValue: de-de
headerName: Referer
headerValue: http://192.168.179.31/
headerName: DNT
headerValue: 1
args: no=0&sw=1
args count: 2
pos 0=@ 2 &@ 4
arg 0 key: no value: 0
pos 5=@ 7 &@ -1
arg 1 key: sw value: 1
args count: 2
Request: /esocket
 Arguments: no=0&sw=1
turning light on

Steckdose ausschalten über Webinterface

New client
method: GET url: /esocket search: no=0&sw=1
headerName: Host
headerValue: 192.168.179.31
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Connection
headerValue: keep-alive
headerName: Accept
headerValue: application/json, text/plain, */*
headerName: User-Agent
headerValue: Mozilla/5.0 (iPad; CPU OS 11_0_2 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A421 Safari/604.1
headerName: Accept-Language
headerValue: de-de
headerName: Referer
headerValue: http://192.168.179.31/
headerName: DNT
headerValue: 1
args: no=0&sw=1
args count: 2
pos 0=@ 2 &@ 4
arg 0 key: no value: 0
pos 5=@ 7 &@ -1
arg 1 key: sw value: 1
args count: 2
Request: /esocket
 Arguments: no=0&sw=1
turning light on
New client
method: GET url: /esocket search: no=0&sw=0
headerName: Host
headerValue: 192.168.179.31
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Connection
headerValue: keep-alive
headerName: Accept
headerValue: application/json, text/plain, */*
headerName: User-Agent
headerValue: Mozilla/5.0 (iPad; CPU OS 11_0_2 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A421 Safari/604.1
headerName: Accept-Language
headerValue: de-de
headerName: Referer
headerValue: http://192.168.179.31/
headerName: DNT
headerValue: 1
args: no=0&sw=0
args count: 2
pos 0=@ 2 &@ 4
arg 0 key: no value: 0
pos 5=@ 7 &@ -1
arg 1 key: sw value: 0
args count: 2
Request: /esocket
 Arguments: no=0&sw=0
turning light off

Brigde in Echo einbinden

New client
method: GET url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1 search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
args:
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1
 Arguments:
Reply by Light
New client
method: GET url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1 search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
args:
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1
 Arguments:
Reply by Light
New client
method: GET url: /description.xml search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
args:
Request: /description.xml
 Arguments:
New client
method: GET url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
args:
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights
 Arguments:
Reply by LightsList

Steckdose über AlexaApp einschalten

New client
method: PUT url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1/state search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length
headerValue: 12
args: {"on": true}
args count: 1
pos 0=@ -1 &@ -1
arg missing value: 0
add plain data
args count: 1
Plain: {"on": true}
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1/state
 Arguments: {"on": true}
Reply by Lightscontrol
0
1
turning light on
Reply by Light
New client
method: GET url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1 search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
args:
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1
 Arguments:
Reply by Light

Steckdose über AlexaApp ausschalten

New client
method: PUT url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1/state search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length
headerValue: 13
args: {"on": false}
args count: 1
pos 0=@ -1 &@ -1
arg missing value: 0
add plain data
args count: 1
Plain: {"on": false}
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1/state
 Arguments: {"on": false}
Reply by Lightscontrol
0
0
turning light off
Reply by Light
New client
method: GET url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1 search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
args:
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1
 Arguments:
Reply by Light

Steckdose über Echo Show Sprachsteuerung einschalten

New client
method: GET url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1 search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
args:
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1
 Arguments:
Reply by Light
New client
method: PUT url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1/state search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length
headerValue: 12
args: {"on": true}
args count: 1
pos 0=@ -1 &@ -1
arg missing value: 0
add plain data
args count: 1
Plain: {"on": true}
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1/state
 Arguments: {"on": true}
Reply by Lightscontrol
0
1
turning light on
Reply by Light
New client
method: GET url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1 search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
args:
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1
 Arguments:
Reply by Light


Steckdose über Echo Show Sprachsteuerung ausschalten

New client
method: PUT url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1/state search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length
headerValue: 13
args: {"on": false}
args count: 1
pos 0=@ -1 &@ -1
arg missing value: 0
add plain data
args count: 1
Plain: {"on": false}
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1/state
 Arguments: {"on": false}
Reply by Lightscontrol
0
0
turning light off
Reply by Light
New client
method: GET url: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1 search:
headerName: Host
headerValue: 192.168.179.31
headerName: Accept
headerValue: */*
args:
Request: /api/cktwYVzBreCUfAt2shIRDZJQTKeVdIZiOgUX9rm0/lights/1
 Arguments:
Reply by Light

Gruß Stefan und danke für Deine Mühe

**Comment by e485s** [comment]
Ich habe jedoch noch eine Problem:
Wenn ich das Board resette bekomme ich bei angestecktem Sendemodul den folgenden Fehler:
Fatal exception (0):
epc1=0x40100003, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

Wenn ich das Sendemodul nach den Start einstecke läuft alles.

Gruß Stefan

**Comment by TTRCmedia** [comment]
Moin!
Gibt´s im Sketch irgendwo einen Schalter für den Log-Level? Kompiliere lieber selber ;)

Habe die Debug-Version getestet:

Einschalten via Webinterface:

> New client
method: GET url: /esocket search: no=0&sw=1
headerName: Host
headerValue: 192.168.0.184
headerName: Connection
headerValue: keep-alive
headerName: Accept
headerValue: application/json, text/plain, */*
headerName: User-Agent
headerValue: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
headerName: Referer
headerValue: http://192.168.0.184/
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Accept-Language
headerValue: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
args: no=0&sw=1
args count: 2
pos 0=@ 2 &@ 4
arg 0 key: no value: 0
pos 5=@ 7 &@ -1
arg 1 key: sw value: 1
args count: 2
Request: /esocket
 Arguments: no=0&sw=1
turning light on


Ausschalten via Webinterface:

> New client
method: GET url: /esocket search: no=0&sw=0
headerName: Host
headerValue: 192.168.0.184
headerName: Connection
headerValue: keep-alive
headerName: Accept
headerValue: application/json, text/plain, */*
headerName: User-Agent
headerValue: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
headerName: Referer
headerValue: http://192.168.0.184/
headerName: Accept-Encoding
headerValue: gzip, deflate
headerName: Accept-Language
headerValue: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
args: no=0&sw=0
args count: 2
pos 0=@ 2 &@ 4
arg 0 key: no value: 0
pos 5=@ 7 &@ -1
arg 1 key: sw value: 0
args count: 2
Request: /esocket
 Arguments: no=0&sw=0
turning light off


Ein via Alexa-App:

> New client
method: GET url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1 search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
args: 
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1
 Arguments: 
Reply by Light
New client
method: PUT url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1/state search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length
headerValue: 12
args: {"on": true}
args count: 1
pos 0=@ -1 &@ -1
arg missing value: 0
add plain data
args count: 1
Plain: {"on": true}
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1/state
 Arguments: {"on": true}
Reply by Lightscontrol
0
1
turning light on
Reply by Light
New client
method: GET url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1 search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
args: 
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1
 Arguments: 
Reply by Light


Aus via Alexa-App:

> New client
method: GET url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1 search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
args: 
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1
 Arguments: 
Reply by Light
New client
method: PUT url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1/state search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length
headerValue: 13
args: {"on": false}
args count: 1
pos 0=@ -1 &@ -1
arg missing value: 0
add plain data
args count: 1
Plain: {"on": false}
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1/state
 Arguments: {"on": false}
Reply by Lightscontrol
0
0
turning light off
Reply by Light
New client
method: GET url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1 search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
args: 
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1
 Arguments: 
Reply by Light


Ein via Sprache:

> New client
method: PUT url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1/state search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length
headerValue: 12
args: {"on": true}
args count: 1
pos 0=@ -1 &@ -1
arg missing value: 0
add plain data
args count: 1
Plain: {"on": true}
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1/state
 Arguments: {"on": true}
Reply by Lightscontrol
0
1
turning light on
Reply by Light
New client
method: GET url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1 search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
args: 
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1
 Arguments: 
Reply by Light


Aus via Sprache:
> New client
method: PUT url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1/state search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
headerName: Content-type
headerValue: application/x-www-form-urlencoded
headerName: Content-Length
headerValue: 13
args: {"on": false}
args count: 1
pos 0=@ -1 &@ -1
arg missing value: 0
add plain data
args count: 1
Plain: {"on": false}
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1/state
 Arguments: {"on": false}
Reply by Lightscontrol
0
0
turning light off
Reply by Light
New client
method: GET url: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1 search: 
headerName: Host
headerValue: 192.168.0.184
headerName: Accept
headerValue: */*
args: 
Request: /api/Xj6AbxopSglrSOQnsgsMptrqVaaMDH1flxdeHRWq/lights/1
 Arguments: 
Reply by Light


Es ist momentan keine echte Steckdose angeschlossen, aber am Oszilloskop sehe ich, dass nur beim Einschalten gesendet wird, beim Ausschalten nicht. Die jetzt sowohl bei der Steuerung über Web, App und Sprache.

**Comment by e485s** [comment]
Kann ich bestätigen bei der Debug Version funktioniert nur das einschalten der Geräte
ausschalten geht nicht.

**Comment by Monarch73** [comment]
Ich hab in der Readme mal eine Beschreibung reingestellt, wie man selbst compiliert:
https://github.com/Monarch73/RFBridge2/blob/master/README.md

Ich hab nur keine Ahnung, wie man in der Arduino IDE debug-symbole bzw compilerflags setzt. Zum benötigten Log-Level muss man das Compilerflag -DDEBUG_ESP_HTTP_SERVER setzen.

> args: name=SteckdoseA&house=11111&code=100000&tri1=&tri2=&url1=&url2=&irhz=&iroff=&iron=

Da stimmt was mit deiner Eingabe nicht. Der Code "100000" hat 6 stellen. Es werden aber nur 5 erwartet.

**Comment by TTRCmedia** [comment]
Compilieren mit der Arduino-IDE klappte in den letzten Tagen ja bereits. Ob es da Compilerflags gibt weis ich nicht, schaue ich mir mal an.

Ich habe 5-stellige Codes verwendet, das Ausschalten klappt trotzdem nicht, daran wird es also eher nicht liegen.

**Comment by Monarch73** [comment]
@tkt2208 und ich können das Problem leider nicht nachvollziehen. Bei uns schalten die Geräte so wie sie sollen. Asche auf mein Haupt, falls ich mich irre, aber ich kann leider nur auf eine Fehlbedienung schließen. Ich habe daher im letzten Release weitere Log-Ausgaben hinzugefügt, die Aufschluß geben sollen, welche Interfaces wie wann geschaltet werden.

Zusätzlich unterstützt das letzte release ein Infarot-Interface, das es erlaubt Geräte per Infrarot zu schalten.

**Comment by TTRCmedia** [comment]
Mit dem Binary des letzten Releases funktioniert es nun auch mit dem Ausschalten (Webinterface, Alexa-App, Sprachsteuerung).

Selbst compiliert allerdings klappt das Ausschalten nicht mit House/Device-Code, aber mit TriState.

EDIT: Noch mal versucht, nu klappt es :)

**Comment by Monarch73** [comment]
Danke für den Info. Damit können wir dieses Thema schließen, denke ich.

**Comment by TTRCmedia** [comment]
Zu früh gefreut... das Binary tut was es soll, die selbst compilierte Version lässt sich nicht über Alexa-App oder Sprachsteuerung schalten. Bei @e485s schaut es ähnlich aus, bzw. zumindest die Sprachsteuerung funktioniert auch dort nicht, wenn selbst compiliert. Library-Versionen entsprechen denen, die Du verwendest, so weit ich das prüfen konnte.

Ich konnte es bislang so weit eingrenzen, dass in WebInterface.cpp, Funktion "LightControlFn(...)", nach Zeile 216...

> JsonObject& root = jsonBuffer.parseObject(onJson);

...der Wert von...

> root.success()

...nie _true_ wird. Somit also kein Schalten, und auch der Status der Lampe (ob an oder aus) wird nicht gesetzt.

**Comment by TTRCmedia** [comment]
Habe einen Verdacht: Ich vermute mal, meine Arduino-IDE hat die falsche Version benutzt. Meine ArduinoJson-Library im Standardpfad hat die selbe Versionsnummer wie die von Dir verwendete (5.12.0), ein Vergleich der Dateien zeigt aber, dass die Versionen unterschiedlich sind...
